tl_task:
  class: sfPropelRouteCollection
  options:
    model:                tlTask
    module:               tl_task
    prefix_path:          /tl_task
    column:               id
    with_wildcard_routes: true
